### ISSUE TITLE
How to build sample applications

### ISSUE THREAD

**Issue by markzolotoy** [Farata/angulartypescript#13]
Even though there is a link to a list of videos it comes down to a huge presentation video which at this point I can't watch. Can you please provide a link to something shorter or I am looking at a wrong link altogether. 

Thanks for the help.

**Comment by yfain** [comment]
This is a repo for the book samples. I'd suggest you buy the book and read it when you'll find the time.

**Comment by markzolotoy** [comment]
I have a book, but previous edition. I thought later examples would make more sense to follow.
