### ISSUE TITLE
Property 'mqAlias' does not exist on type 'MediaChange[]'

### ISSUE THREAD

**Issue by THCKwarter** [Farata/angulartypescript#17]
Ch7, in `home.component.ts`:

```
constructor(private media: MediaObserver, private productService: ProductService) {
    this.products$ = this.productService.getAll();

    this.columns$ = this.media.asObservable()
      .pipe(
         map(mc => <number>this.breakpointsToColumnsNumber.get(mc.mqAlias))
       );
  }
```

`mc.mqAlias` gives the error: `Property 'mqAlias' does not exist on type 'MediaChange[]'.`

**Comment by hdouglassjr** [comment]
Simply replace "asObservable()" with "media$" as shown:

`constructor(private media: MediaObserver, private productService: ProductService)
  {

    this.productService.getAll();

    this.columns$ = this.media.media$
      .pipe(
        map(mc => <number>this.breakpointsToColumnsNumber.get(mc.mqAlias))
      );
  }`

**Comment by yfain** [comment]
I believe we fixed it in the code for A7.

**Comment by ArnoldoR** [comment]
@Component({
  selector: 'app-root',
  template: `<h3>Watch the breakpoint activation messages in the console.</h3>
  <span *ngIf="showExtra">Showing extra info on medium screens</span><br/>
  <span *ngIf="this.mediaObserver.isActive('md')">Showing extra info on medium screens with isActive</span>

  `
})
export class AppComponent {
  public watcher: Subscription;
  //
  showExtras$: Observable<boolean>;
  public showExtra: boolean;
  activeMediaQuery = '';
 
  constructor(public mediaObserver: MediaObserver) {
    this.watcher = this.mediaObserver.media$.subscribe((change: MediaChange) => {
     console.log(change);
     console.log("mqAlias="+change.mqAlias); 
     this.showExtra=change.mqAlias==='md'? true:false;
     return change.mqAlias==='md'? true:false;
    });
  }
}
