### ISSUE TITLE
Chapter 2 navbar

### ISSUE THREAD

**Issue by jrobm2k9** [Farata/angulartypescript#20]
The navbar is not working, I copied the code from the repository but the navbar is just text instead of a navbar like this: 

ngAuction
Home (current)
About
Services
Find productsPlace order
Pay
search works!

footer works!

I checked my angular.json styles and scripts and they are exactly what you have, I'm using angular 8 and bootstrap 4.3.1 though, I know there are issues with bootstrap and angular should i just switch to ng-bootstrap? Or do you have a work around?  Really enjoying the book so far though, thanks!

**Comment by yfain** [comment]
There are no issues with the Bootstrap Navbar. Check the code samples for Angular 8

**Comment by jrobm2k9** [comment]
Under chapter 2?  I didn't see the ngAuction app under that chapter.

**Comment by yfain** [comment]
Just put s version of ngAuction. Please let me know if it matched the description in the chapter.

**Comment by jrobm2k9** [comment]
So I think there is an issue with my machine, I downloaded the angulartypescript-master and opened the project and it worked perfectly but my code is not producing the same results.  I'll try and figure out what the issue is, thanks for your help!
