### ISSUE TITLE
ObservableMedia deprecated?

### ISSUE THREAD

**Issue by Mesqualito** [Farata/angulartypescript#21]
My compiler moans regarding https://github.com/Farata/angulartypescript/blob/master/code-samples/Angular7/chapter7/ng-auction/src/app/home/home.component.ts. It seems ObservableMedia is deprecated: https://github.com/angular/flex-layout/issues/989. Do I have to update my code accordingly to be able to follow your book?

**Comment by yfain** [comment]
I believe it was fixed on the Angular8 version of the book code samples.

**Comment by Mesqualito** [comment]
I solved it for myself [here](https://github.com/Mesqualito/Angular-Auction/blob/ngAuction_v2/src/app/home/home.component.ts) with using

```
constructor(private media: MediaObserver, private productService: ProductService) {
    this.products$ = this.productService.getAll();
    this.columns$ = this.media.asObservable().pipe(
      map(mc => <number>this.breakpointsToColumnsNumber.get(mc[0].mqAlias))
    );
  }
```

Of course, I am not shure if this is very clever - I am a beginner ;-)

I didn't find the concerning changes in your repo and it stopped me at this point to be able to carry on with learning - or I would have to step back to Angular 6. In the upcoming chapters, the code for your book is divided into server and client, maybe I'll find it somewhere in the next days :-)

_**Thank you for your good work - the book is very recommendable, a good composition to learn along in an ever changing vocation with lots of details and valuable hints!**_

**Comment by Mesqualito** [comment]
**Hint:**
The replacement in https://github.com/Farata/angulartypescript/blob/master/code-samples/Angular8/chapter13/ng-auction/client/src/app/product/product-suggestion/product-suggestion.component.ts and https://github.com/Farata/angulartypescript/blob/master/code-samples/Angular8/chapter13/ng-auction/client/src/app/home/product-grid/product-grid.component.ts is also marked as deprecated.

**Comment by yfain** [comment]
@Mesqualito Thank you for your feedback!
