### ISSUE TITLE
chapter 3 - trying to build the app... (as you have in the manning Angular with TypeScript2 book

### ISSUE THREAD

**Issue by cpkrish123** [Farata/angulartypescript#26]
Using Angular 12
and have "strict Mode" turned on ... while generating my app.

Getting these errors

Error: src/app/product-detail/product-detail.component.ts:12:3 - error TS2564: Property 'product' has no initializer and is not definitely assigned in the constructor.

12   product: Product;
     ~~~~~~~


Error: src/app/product-item/product-item.component.ts:11:12 - error TS2564: Property 'product' has no initializer and is not definitely assigned in the constructor.

11   @Input() product: Product;
              ~~~~~~~

Error: src/app/shared/product.service.ts:29:5 - error TS2322: Type '{ id: number; title: string; price: number; rating: number; description: string; categories: string[]; } | undefined' is not assignable to type 'Product'.
  Type 'undefined' is not assignable to type 'Product'.

29     return products.find(p => p.id === productId);
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

My code is exactly identlcal to what is on the github site (as far as I can see)

I do not find a products.find () method anywhere
also get errors about "product" being undefined.

Please help!

**Comment by yfain** [comment]
We've never tested the code with Angular 12. Just initialize the property product either on declaration or in the constructor as the error message suggests.

**Comment by cpkrish123** [comment]
What about products.find method --> it is not defined anywhere? How does it work? 

When you say initialize the property product - what is the default value? 

In Product-item it is decorated with @Input as well. What is the initializer value for that? 

Sorry to request help again. For someone buying the book today - angular 12 is the downloadable version. 
and that is what I have. I am trying to learn the tool - and stuck with these errors. 
Please help!
